FROM strapi/base

RUN apt-get update
RUN apt-get -y install curl
RUN apt-get install libnspr4 libnss3 libnss3-tools
RUN wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
RUN dpkg -i google-chrome-stable_current_amd64.deb; apt-get -fy install

WORKDIR /
COPY ./plugins/ ./plugins/
COPY ./extensions/ ./extensions/

COPY ./strapi-starters/corporate/backend/ ./
RUN yarn install

COPY . .

WORKDIR /plugins/cms-analyzer
RUN yarn install

WORKDIR /

COPY . .

#ENV NODE_ENV production

RUN yarn build

EXPOSE 1337

CMD ["yarn", "start"]
