FROM node:14

ENV PORT 3000

ARG NEXT_PUBLIC_STRAPI_API_URL
ENV NEXT_PUBLIC_STRAPI_API_URL=$NEXT_PUBLIC_STRAPI_API_URL

# Create app directory
WORKDIR /

# Installing dependencies
COPY package*.json /
RUN yarn install

# Copying source files
COPY . .

# Building app
RUN yarn run build
RUN yarn next telemetry disable

EXPOSE 3000

# Running the app
CMD "yarn" "start"